package com.stardust.datebase.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.stardust.auojs.inrt.bean.NewTaskBean;
import com.stardust.datebase.greenDao.bean.History;

import com.stardust.datebase.greenDao.NewTaskBeanDao;
import com.stardust.datebase.greenDao.HistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newTaskBeanDaoConfig;
    private final DaoConfig historyDaoConfig;

    private final NewTaskBeanDao newTaskBeanDao;
    private final HistoryDao historyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newTaskBeanDaoConfig = daoConfigMap.get(NewTaskBeanDao.class).clone();
        newTaskBeanDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        newTaskBeanDao = new NewTaskBeanDao(newTaskBeanDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);

        registerDao(NewTaskBean.class, newTaskBeanDao);
        registerDao(History.class, historyDao);
    }
    
    public void clear() {
        newTaskBeanDaoConfig.clearIdentityScope();
        historyDaoConfig.clearIdentityScope();
    }

    public NewTaskBeanDao getNewTaskBeanDao() {
        return newTaskBeanDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

}
