package com.stardust.datebase.greenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.stardust.auojs.inrt.bean.NewTaskBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NEW_TASK_BEAN".
*/
public class NewTaskBeanDao extends AbstractDao<NewTaskBean, String> {

    public static final String TABLENAME = "NEW_TASK_BEAN";

    /**
     * Properties of entity NewTaskBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property F_PackageName = new Property(0, String.class, "f_PackageName", true, "F__PACKAGE_NAME");
        public final static Property F_AppName = new Property(1, String.class, "f_AppName", false, "F__APP_NAME");
        public final static Property F_AppVersion = new Property(2, String.class, "f_AppVersion", false, "F__APP_VERSION");
        public final static Property TotalNumber = new Property(3, int.class, "totalNumber", false, "TOTAL_NUMBER");
        public final static Property SlidingSpeed = new Property(4, int.class, "slidingSpeed", false, "SLIDING_SPEED");
        public final static Property WaitForTime = new Property(5, int.class, "waitForTime", false, "WAIT_FOR_TIME");
        public final static Property SingleSlideTimes = new Property(6, int.class, "singleSlideTimes", false, "SINGLE_SLIDE_TIMES");
        public final static Property SlidingInterval = new Property(7, int.class, "slidingInterval", false, "SLIDING_INTERVAL");
        public final static Property IsExecuted = new Property(8, boolean.class, "isExecuted", false, "IS_EXECUTED");
        public final static Property IsExecutedSussed = new Property(9, boolean.class, "isExecutedSussed", false, "IS_EXECUTED_SUSSED");
        public final static Property Sort = new Property(10, int.class, "sort", false, "SORT");
    }


    public NewTaskBeanDao(DaoConfig config) {
        super(config);
    }
    
    public NewTaskBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEW_TASK_BEAN\" (" + //
                "\"F__PACKAGE_NAME\" TEXT PRIMARY KEY NOT NULL ," + // 0: f_PackageName
                "\"F__APP_NAME\" TEXT," + // 1: f_AppName
                "\"F__APP_VERSION\" TEXT," + // 2: f_AppVersion
                "\"TOTAL_NUMBER\" INTEGER NOT NULL ," + // 3: totalNumber
                "\"SLIDING_SPEED\" INTEGER NOT NULL ," + // 4: slidingSpeed
                "\"WAIT_FOR_TIME\" INTEGER NOT NULL ," + // 5: waitForTime
                "\"SINGLE_SLIDE_TIMES\" INTEGER NOT NULL ," + // 6: singleSlideTimes
                "\"SLIDING_INTERVAL\" INTEGER NOT NULL ," + // 7: slidingInterval
                "\"IS_EXECUTED\" INTEGER NOT NULL ," + // 8: isExecuted
                "\"IS_EXECUTED_SUSSED\" INTEGER NOT NULL ," + // 9: isExecutedSussed
                "\"SORT\" INTEGER NOT NULL );"); // 10: sort
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEW_TASK_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NewTaskBean entity) {
        stmt.clearBindings();
 
        String f_PackageName = entity.getF_PackageName();
        if (f_PackageName != null) {
            stmt.bindString(1, f_PackageName);
        }
 
        String f_AppName = entity.getF_AppName();
        if (f_AppName != null) {
            stmt.bindString(2, f_AppName);
        }
 
        String f_AppVersion = entity.getF_AppVersion();
        if (f_AppVersion != null) {
            stmt.bindString(3, f_AppVersion);
        }
        stmt.bindLong(4, entity.getTotalNumber());
        stmt.bindLong(5, entity.getSlidingSpeed());
        stmt.bindLong(6, entity.getWaitForTime());
        stmt.bindLong(7, entity.getSingleSlideTimes());
        stmt.bindLong(8, entity.getSlidingInterval());
        stmt.bindLong(9, entity.getIsExecuted() ? 1L: 0L);
        stmt.bindLong(10, entity.getIsExecutedSussed() ? 1L: 0L);
        stmt.bindLong(11, entity.getSort());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NewTaskBean entity) {
        stmt.clearBindings();
 
        String f_PackageName = entity.getF_PackageName();
        if (f_PackageName != null) {
            stmt.bindString(1, f_PackageName);
        }
 
        String f_AppName = entity.getF_AppName();
        if (f_AppName != null) {
            stmt.bindString(2, f_AppName);
        }
 
        String f_AppVersion = entity.getF_AppVersion();
        if (f_AppVersion != null) {
            stmt.bindString(3, f_AppVersion);
        }
        stmt.bindLong(4, entity.getTotalNumber());
        stmt.bindLong(5, entity.getSlidingSpeed());
        stmt.bindLong(6, entity.getWaitForTime());
        stmt.bindLong(7, entity.getSingleSlideTimes());
        stmt.bindLong(8, entity.getSlidingInterval());
        stmt.bindLong(9, entity.getIsExecuted() ? 1L: 0L);
        stmt.bindLong(10, entity.getIsExecutedSussed() ? 1L: 0L);
        stmt.bindLong(11, entity.getSort());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public NewTaskBean readEntity(Cursor cursor, int offset) {
        NewTaskBean entity = new NewTaskBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // f_PackageName
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // f_AppName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // f_AppVersion
            cursor.getInt(offset + 3), // totalNumber
            cursor.getInt(offset + 4), // slidingSpeed
            cursor.getInt(offset + 5), // waitForTime
            cursor.getInt(offset + 6), // singleSlideTimes
            cursor.getInt(offset + 7), // slidingInterval
            cursor.getShort(offset + 8) != 0, // isExecuted
            cursor.getShort(offset + 9) != 0, // isExecutedSussed
            cursor.getInt(offset + 10) // sort
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NewTaskBean entity, int offset) {
        entity.setF_PackageName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setF_AppName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setF_AppVersion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTotalNumber(cursor.getInt(offset + 3));
        entity.setSlidingSpeed(cursor.getInt(offset + 4));
        entity.setWaitForTime(cursor.getInt(offset + 5));
        entity.setSingleSlideTimes(cursor.getInt(offset + 6));
        entity.setSlidingInterval(cursor.getInt(offset + 7));
        entity.setIsExecuted(cursor.getShort(offset + 8) != 0);
        entity.setIsExecutedSussed(cursor.getShort(offset + 9) != 0);
        entity.setSort(cursor.getInt(offset + 10));
     }
    
    @Override
    protected final String updateKeyAfterInsert(NewTaskBean entity, long rowId) {
        return entity.getF_PackageName();
    }
    
    @Override
    public String getKey(NewTaskBean entity) {
        if(entity != null) {
            return entity.getF_PackageName();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NewTaskBean entity) {
        return entity.getF_PackageName() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
